apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-nginx
  namespace: k8spart1
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', 'date; curl -I -s -o /dev/null -w "Status %{http_code}\n" 35.205.170.73:31000']
          restartPolicy: OnFailure